# Generated by Django 3.0.2 on 2020-02-13 18:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome_grupo', models.CharField(max_length=60, verbose_name='Nome do Grupo')),
                ('dirigente', models.CharField(max_length=60, verbose_name='Dirigente do Gurpo')),
                ('local_grupo', models.CharField(max_length=80, verbose_name='Local do Grupo')),
                ('endereco_grupo', models.TextField(blank=True, max_length=200, null=True, verbose_name='Endereço Grupo')),
                ('dia_saida', models.IntegerField(blank=True, choices=[(1, 'Domingo'), (2, 'Segunda'), (3, 'Terça'), (4, 'Quarta'), (5, 'Quinta'), (6, 'Sexta'), (7, 'Sábado')], default=1, null=True, verbose_name='Dia da Saída')),
                ('horario', models.TimeField(blank=True, null=True, verbose_name='Horário da Saída')),
                ('obs', models.TextField(max_length=200, verbose_name='Observação')),
            ],
        ),
        migrations.CreateModel(
            name='Publicador',
            fields=[
                ('id_publicador', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome_publicador', models.CharField(max_length=60, verbose_name='Nome do Publicador')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('esperanca_pub', models.CharField(choices=[('OO', 'Outras Ovelhas'), ('UG', 'Ungido')], default='OO', max_length=2, verbose_name='Esperança')),
                ('data_batismo', models.DateField(blank=True, null=True, verbose_name='Data de Batismo')),
                ('atuacao_pub', models.CharField(choices=[('Pb', 'Publicador'), ('Pa', 'Pioneiro Auxiliar'), ('Pr', 'Pioneiro Regular'), ('Pes', 'Pioneiro Especial')], max_length=3, verbose_name='Atuação')),
                ('privilegio_pub', models.CharField(blank=True, choices=[('Sm', 'Servo Ministerial'), ('Ac', 'Ancião')], max_length=2, null=True, verbose_name='Privilégio')),
                ('tel_fixo', models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefone Fixo')),
                ('tel_celular', models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefone Celular')),
                ('endereco_pub', models.TextField(blank=True, max_length=200, null=True, verbose_name='Endereço')),
                ('grupo_pub', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publicadores.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id_atividade', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('mes_relatorio', models.IntegerField(verbose_name='Mês')),
                ('ano_relatorio', models.IntegerField(verbose_name='Ano')),
                ('publicacoes', models.IntegerField(verbose_name='Publicações')),
                ('videos', models.IntegerField(verbose_name='Vídeos')),
                ('horas', models.FloatField(verbose_name='Horas')),
                ('revisitas', models.IntegerField(verbose_name='Revisitas')),
                ('estudos', models.IntegerField(verbose_name='Estudos')),
                ('obs_relatorio', models.TextField(blank=True, max_length=200, null=True, verbose_name='Observação')),
                ('publicador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publicadores.Publicador')),
            ],
        ),
    ]
