# Generated by Django 3.0.2 on 2020-02-13 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividade',
            options={'ordering': ['mes_relatorio', 'ano_relatorio', 'publicador']},
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['nome_grupo']},
        ),
        migrations.AlterModelOptions(
            name='publicador',
            options={'ordering': ['nome_publicador', 'grupo_pub']},
        ),
    ]
