# Generated by Django 3.0.2 on 2020-02-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicadores', '0002_auto_20200213_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='obs',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Observação'),
        ),
    ]
