# Generated by Django 3.0.2 on 2020-02-13 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicadores', '0003_auto_20200213_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicador',
            name='grupo_pub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publicadores.Grupo', verbose_name='Grupo Publicador'),
        ),
    ]
