# Generated by Django 3.0.2 on 2020-02-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicadores', '0004_auto_20200213_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicador',
            name='genero',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], default='M', max_length=2, verbose_name='Genero'),
        ),
    ]
