# Generated by Django 3.0.2 on 2020-02-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicadores', '0005_publicador_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='mes_relatorio',
            field=models.IntegerField(default=1, verbose_name='Mês'),
        ),
    ]
