# Generated by Django 3.0.2 on 2020-02-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicadores', '0006_auto_20200213_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='mes_relatorio',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], default=1, verbose_name='Mês'),
        ),
    ]
