# Generated by Django 3.0.2 on 2020-03-09 19:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('publicadores', '0007_auto_20200213_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='ano_relatorio',
            field=models.IntegerField(default=2020, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='id_atividade',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='mes_relatorio',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], default=2, verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='id_grupo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publicador',
            name='id_publicador',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
